openapi: 3.0.3
info:
  title: DBTest Users API
  description: |-
    Documentation for the users API of the dbtest database.
  version: 1.0.0
servers:
  - url: https://localhost/api/
tags:
  - name: users
    description: Operations about user
paths:
  /tp4/api/index.php:
    get:
      tags:
        - users
      summary: Get users list.
      description: Return the list of users in JSON format.
      operationId: usersGet
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 15
                    name:
                      type: string
                      example: mister
                    email:
                      type: string
                      example: mister@free.fr
    post:
      tags:
        - users
      summary: Add a new user.
      description: Add a new user.
      operationId: usersPost
      requestBody:
        description: Send a json to create user.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      responses:
        '201':
          description: Successfully created
          content:
            text/plain:
              schema:
                type: string
                example: Successfully created user 15
        '400':
          description: Wrong parameters
        '500':
          description: Internal server error
          
  /tp4/api/index.php/{id}:
    put:
      tags:
        - users
      summary: Update an user.
      description: Change the name and email of an user.
      operationId: usersPut
      requestBody:
        description: Send a json to update user.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      parameters:
        - name: id
          in: path
          description: ID of the user.
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '202':
          description: Successfully updated
          content:
            text/plain:
              schema:
                type: string
                example: Successfully updated user 15
        '400':
          description: Wrong parameters OR missing parameters OR wrong Content-Type in request header.
        '500':
          description: Internal server error.
    delete:
      tags:
        - users
      summary: Delete an user.
      operationId: usersDelete
      parameters:
        - name: id
          in: path
          description: ID of the user.
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '202':
          description: Successfully deleted
          content:
            text/plain:
              schema:
                type: string
                example: Successfully deleted user 15
        '400':
          description: No user with this id.
        '500':
          description: Internal server error.
components:
  schemas:
    User:
      required:
        - name
        - email
      type: object
      properties:
        name:
          type: string
          example: mister
        email:
          type: string
          example: mister@free.fr